

def MICN_ECL_96(args,pred_len = 96):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "MICN"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 96
    args.pred_len = pred_len
    args.e_layers = 2
    args.d_layers = 1
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.d_model = 256
    args.d_ff = 512
    args.top_k = 5
    args.des = "Exp"
    args.itr = 1

def MICN_ECL_192(args,pred_len = 192):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "MICN"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 96
    args.pred_len = pred_len
    args.e_layers = 2
    args.d_layers = 1
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.d_model = 256
    args.d_ff = 512
    args.top_k = 5
    args.des = "Exp"
    args.itr = 1

def MICN_ECL_336(args,pred_len = 336):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "MICN"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 96
    args.pred_len = pred_len
    args.e_layers = 2
    args.d_layers = 1
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.d_model = 256
    args.d_ff = 512
    args.top_k = 5
    args.des = "Exp"
    args.itr = 1

def MICN_ECL_720(args,pred_len = 720):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "MICN"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 96
    args.pred_len = pred_len
    args.e_layers = 2
    args.d_layers = 1
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.d_model = 256
    args.d_ff = 512
    args.top_k = 5
    args.des = "Exp"
    args.itr = 1

