

def TimeXer_ECL_96(args,pred_len = 96):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "TimeXer"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 48
    args.pred_len = pred_len
    args.e_layers = 4
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.des = "Exp"
    args.d_ff = 512
    args.batch_size = 64
    args.itr = 1

def TimeXer_ECL_192(args,pred_len = 192):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "TimeXer"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 48
    args.pred_len = pred_len
    args.e_layers = 4
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.des = "Exp"
    args.d_ff = 512
    args.batch_size = 64
    args.itr = 1

def TimeXer_ECL_336(args,pred_len = 336):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "TimeXer"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 48
    args.pred_len = pred_len
    args.e_layers = 4
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.des = "Exp"
    args.d_ff = 512
    args.batch_size = 64
    args.itr = 1

def TimeXer_ECL_720(args,pred_len = 720):
    args.task_name = "long_term_forecast"
    args.is_training = 1
    args.root_path = "./dataset/electricity/"
    args.data_path = "electricity.csv"
    args.model_id = "ECL_96_"+str(pred_len)
    args.model = "TimeXer"
    args.data = "custom"
    args.features = "M"
    args.seq_len = 96
    args.label_len = 48
    args.pred_len = pred_len
    args.e_layers = 4
    args.factor = 3
    args.enc_in = 321
    args.dec_in = 321
    args.c_out = 321
    args.des = "Exp"
    args.d_ff = 512
    args.batch_size = 64
    args.itr = 1